# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/action

name: Build and deploy container app to Azure Web App - Recruitradar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    env:
      NODE_ENV: development
      SECRET: ${{ secrets.SECRET }}
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: pgrecruit.postgres.database.azure.com
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: pgadmin
      TYPEORM_PASSWORD: ${{ secrets.TYPEORM_PASSWORD }}
      TYPEORM_DATABASE: recruitradar

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://recruitradar.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e9eb7af0ecbd41ebada045b51879ebfe }}
        password: ${{ secrets.AzureAppService_ContainerPassword_862a4bf5ce0d4ed3abb887f487ad5c05 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./backend  # Aqui você define o contexto como a pasta backend
        push: true
        tags: recruitradar.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e9eb7af0ecbd41ebada045b51879ebfe }}/recruitradar-backend:${{ github.sha }}
        file: ./backend/Dockerfile
        build-args: |
          NODE_ENV=development
          SECRET=${{ secrets.SECRET }}
          TYPEORM_CONNECTION=postgres
          TYPEORM_HOST=pgrecruit.postgres.database.azure.com
          TYPEORM_PORT=5432
          TYPEORM_USERNAME=pgadmin
          TYPEORM_PASSWORD=${{ secrets.TYPEORM_PASSWORD }}
          TYPEORM_DATABASE=recruitradar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Recruitradar'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8465e4bd806543349fdbd20e99313e03 }}
        images: 'recruitradar.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e9eb7af0ecbd41ebada045b51879ebfe }}/recruitradar-backend:${{ github.sha }}'
